name: 0xfPix
main: io.qzz._0xflucas.PixPlugin
version: 1.1
depend: []
author: 0xflucas
commands:
  shop:
    description: Plugin para compras de item com Pix.
    usage: /shop <args>
    aliases: [pix]